### ISSUE TITLE
QML on Julia 1.0.1

### ISSUE THREAD

**Issue by jheinen** [barche/QML.jl#59] opened 2018-10-26 10:33 UTC
Are there plans to support Julia 1.0.1?

```
(v1.0) pkg> add QML:master
  Updating registry at `/usr/local/lib/julia/v1.0/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Cloning git-repo `QML:master`
ERROR: failed to clone from QML:master, error: GitError(Code:ERROR, Class:Net, failed to resolve address for QML: nodename nor servname provided, or not known)

(v1.0) pkg> add QML#master
   Cloning git-repo `https://github.com/barche/QML.jl.git`
  Updating git-repo `https://github.com/barche/QML.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package CxxWrap [1f15a43c]:
 CxxWrap [1f15a43c] log:
 ├─possible versions are: [0.1.0-0.1.8, 0.2.0-0.2.3, 0.3.0-0.3.1, 0.4.0-0.4.1, 0.5.0, 0.6.0-0.6.1, 0.7.0-0.7.4, 0.8.0-0.8.1] or uninstalled
 ├─restricted to versions 0.5.0-0.5 by QML [2db162a6], leaving only versions 0.5.0
 │ └─QML [2db162a6] log:
 │   ├─possible versions are: 0.4.3 or uninstalled
 │   └─QML [2db162a6] is fixed to version 0.4.3+
 └─restricted to versions 0.8.1 by an explicit requirement — no versions left
```

I'm on CxxWrap 0.8.1.

**Comment by barche** [comment] 2018-10-26 14:49
Yes, working on it 😉

Closing as duplicate of #57

**Closed by barche** 2018-10-26 14:49 UTC
